### ISSUE TITLE
Make website mobile responsive

### ISSUE THREAD

**Issue by sahanmndl** [sahanmndl/UpCoding-Web#10]
Make website to function properly on mobiles/tablets etc.

**Comment by hfr58gb** [comment]
can i you assign this issue to me

**Comment by anuragK-24** [comment]
can you assign this issue to me

**Comment by sahanmndl** [comment]
Please let me know if you are working / will work on this or not

**Comment by anuragK-24** [comment]
Sorry
Not working, been in some work
U can assign to other

**Comment by sahanmndl** [comment]
Alright 👍
