### ISSUE TITLE
Fix the duration bug

### ISSUE THREAD

**Issue by sahanmndl** [sahanmndl/UpCoding-Web#19]
- Show correct time difference in the `duration` column
- If duration is less than a day, show in format `HH:MM:SS`
- If duration is less than 30 days, show in format `DD:HH:MM:SS`
- Else, just show in terms of `Months` or `Years`

**Comment by Nevilkumar** [comment]
Hi @sahanmndl I would like to work on this issue. Can you please assign it to me?

**Comment by jsvigneshkanna** [comment]
Hi @sahanmndl , Please assign me this issue as am new to contributions and have good knowledge in reactJS

**Comment by TanishkM** [comment]
Can i do this?

**Comment by Nevilkumar** [comment]
@sahanmndl what if the duration is of 45 days & 2 hr, then what needs to be displayed?

**Comment by sahanmndl** [comment]
> @sahanmndl what if the duration is of 45 days & 2 hr, then what needs to be displayed?

I think it would be better if any duration is greater than 24hrs, just display it as closest days count. 
So, 26 hrs = 1 day, 40 hrs = 2 days and 45 days 2hrs = 45 days.

Rest is up to you, whatever u think is best and can be properly implemented.

**Comment by Nevilkumar** [comment]
cool thanks!!
