### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by sahanmndl** [sahanmndl/UpCoding-Web#3]
Set dark mode toggle on header

**Comment by TanishkM** [comment]
I want to work on this .Can I get assigned to this issue?

**Comment by karnikagupta30** [comment]
@sahanmndl can you assign me this issue?

**Comment by sahanmndl** [comment]
> @sahanmndl can you assign me this issue?

Sorry, I have already assigned this issue to someone. I will probably open few more issues later today, if you want you can ask then.

**Comment by karnikagupta30** [comment]
> > @sahanmndl can you assign me this issue?
> 
> Sorry, I have already assigned this issue to someone. I will probably open few more issues later today, if you want you can ask then.

Sure
