### ISSUE TITLE
User stats page | Codeforces

### ISSUE THREAD

**Issue by sahanmndl** [sahanmndl/UpCoding-Web#36]
When user enters any username under Codeforces in the "User Stats" page, it should display a block below that display all relevant details and statistics about that user, using charts or graphs wherever relevant. Use codeforces API for this.

**Comment by thesloppyguy** [comment]
Hey Sahan, Can you assign this issue to me, I can get this done for you.

**Comment by sahanmndl** [comment]
Assigned

**Comment by thesloppyguy** [comment]
I have made a PR for the same, please review it when possible.

**Comment by sahanmndl** [comment]
Merged

**Comment by sahanmndl** [comment]
Just wanted to ask, can you add background colors to the rating curve like Codeforces does? You can make a seperate PR for that and I will merge it along with the hacktoberfest labels.

**Comment by thesloppyguy** [comment]
Made a PR with background colors to the rating curve as suggested by you. Please review when possible and add the hacktoberfest labels if possible.
