### ISSUE TITLE
Add Footer

### ISSUE THREAD

**Issue by Shruti0316** [sahanmndl/UpCoding-Web#37]
We can have a footer at the end saying "copyright reserved" or something else you find more suitable. We can also add contacts so that developers/users can reach out to us and give feedback.
I would like to implement this feature. Please assign it to me.
Thanks.

**Comment by Chetax** [comment]
i want to work on this issue can you please assign it to me

**Comment by sahanmndl** [comment]
I have already issued it to someone else

**Comment by Chetax** [comment]
Ok Sir It's Fine
