### ISSUE TITLE
User Stats | CodeChef

### ISSUE THREAD

**Issue by sahanmndl** [sahanmndl/UpCoding-Web#40]
When user enters any username under CodeChef in the "User Stats" page, it should display a block below that display all relevant details and statistics about that user, using charts or graphs wherever relevant (please refer to the user stats for Codeforces). Use CodeChef official API (if available) or any other 3rd party API if possible.

**Comment by itsjustneo-xo** [comment]
I'd like to work on this

**Comment by itsjustneo-xo** [comment]
The Official CodeChef API is restricted and unofficial APIs are currently not working
