### ISSUE TITLE
User Stats | LeetCode

### ISSUE THREAD

**Issue by sahanmndl** [sahanmndl/UpCoding-Web#41]
When user enters any username under LeetCode in the "User Stats" page, it should display a block below that display all relevant details and statistics about that user, using charts or graphs wherever relevant (please refer to the user stats for Codeforces). Use LeetCode official API (if available) or any other 3rd party API if possible.

**Comment by andrefpoliveira** [comment]
Hey! Can I work on this for Hacktoberfest? 😁

**Comment by sahanmndl** [comment]
Assigned

**Comment by sahanmndl** [comment]
Let me know if you are / will be working on this.

**Comment by andrefpoliveira** [comment]
Yeah I'm working on it 😁
