### ISSUE TITLE
Dropdown menu for Practice button

### ISSUE THREAD

**Issue by sahanmndl** [sahanmndl/UpCoding-Web#44]
Currently on clicking "Practice" button in the header, it opens the GFG Practice link. But it should be changed.
On clicking Practice, it should open a dropdown menu, with three options, clicking which will open the respective links.

- LeetCode: https://leetcode.com/problemset/all/
- Codeforces: https://codeforces.com/problemset
- GeeksForGeeks: https://practice.geeksforgeeks.org/explore?page=1&sortBy=submissions

**Comment by joshijoe05** [comment]
Hello, i would like to work on this issue please assign this to me

**Comment by Madhura-saw** [comment]
Hi @sahanmndl, Could this issue be assigned to me?

**Comment by aman4uas** [comment]
Hello @sahanmndl, Can you please assign this task to me !!

**Comment by Preetraj2002** [comment]
HEY !!! @sahanmndl . It's a cool opportunity for me to make my initial contributions in open-source. Kindly assign me this task

**Comment by sahanmndl** [comment]
Hi @joshijoe05 @Madhura-saw @aman4uas @Preetraj2002  , since there are 4 people, please let me know what extra changes you can make, other than what mentioned. If no replies, then I will assign @joshijoe05 since he is first.

**Comment by Preetraj2002** [comment]
i would also add icons before the button (or links)

**Comment by Madhura-saw** [comment]
I can add icons and also make a searchable dropdown

**Comment by Preetraj2002** [comment]
Hey @sahanmndl can me and @Madhura-saw both work on this issue I will add the drop-down and then create a new issue in which he can add searchable drop down

**Comment by sahanmndl** [comment]
Ok, assigned to @Preetraj2002 and @Madhura-saw

**Comment by Madhura-saw** [comment]
Hey @sahanmndl I have already cloned this repo and was waiting for changes made by @Preetraj2002 so that I can add search bar for dropdown on top, should I go ahead with it?

**Comment by sahanmndl** [comment]
Sure, make a new PR and I will add the labels and merge
