### ISSUE TITLE
"Practice" dropdown menu arrow

### ISSUE THREAD

**Issue by sahanmndl** [sahanmndl/UpCoding-Web#47]
- Show a dropdown menu arrow beside the "Practice" button matching the color scheme (light/dark mode)
- Change the background ripple of "Practice" from oval to rectangular to match that of "Upcoming" or "Ongoing"

**Comment by 1-ankush-1** [comment]
Hey assign this issue to me . 
suggestion - you should add screenshots for more clarifications of issues.

**Comment by ShubhamSingh-S34** [comment]
Hey I have generated a pull request regarding this issue
