### ISSUE TITLE
Sorting with respect to Coding platform

### ISSUE THREAD

**Issue by bhumika-1-3** [sahanmndl/UpCoding-Web#5]
Selecting a perfect platform is very important when It comes to competitive programming.
 ![image](https://user-images.githubusercontent.com/80103105/194558659-da262d09-4bab-491d-9c59-459ab6709fc0.png)

**Comment by bhumika-1-3** [comment]
.

**Comment by sahanmndl** [comment]
> .

Nice addition! U can submit a PR if u want

**Comment by bhumika-1-3** [comment]
Submitted the PR
