### ISSUE TITLE
Invalid Date

### ISSUE THREAD

**Issue by itsjustneo-xo** [sahanmndl/UpCoding-Web#50]
# Preview

![image](https://github.com/sahanmndl/UpCoding-Web/assets/70348851/d41796e5-0f6f-41f8-a8d1-879bc0b1745c)

**Comment by sahanmndl** [comment]
Can you fix it? I have tried many times, it works on few PCs and not on others, I don't know why.

**Comment by itsjustneo-xo** [comment]
I can give it a try :D
